# Data importing

In [151]:
import pandas as pd
import numpy as np

In [152]:
df= pd.read_csv(r"C:\Users\Vaishnavi Daule\Downloads\customer (1).csv")

In [153]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [154]:
df.sample(5)

    age  gender   review education purchased
38   45  Female     Good    School        No
48   39  Female     Good        UG       Yes
41   23    Male     Good        PG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes

## insights
* gender column is nominal categorical variable.
* review column is ordinal categorical variable.
* eduction column is ordinal categorical variable.
* purchased column is nominal categorical variable.

## Counts the value

In [155]:
df["review"].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [156]:
df["gender"].value_counts()

gender
Female    29
Male      21
Name: count, dtype: int64

In [157]:
df["education"].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [158]:
df["purchased"].value_counts()

purchased
No     26
Yes    24
Name: count, dtype: int64

In [159]:
df= df.iloc[:,2:]

In [160]:
df.head(15)

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes

## insights 
* we are apply ordinal ecoding on review and education column.
* and we are apply label encoding on purchased column

# Split the data in train and test

In [182]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[["review", "education"]],
                                                    df["purchased"],
                                                    test_size=0.20,
                                                    random_state=42)

## insights
* here we split the data into train and test 
* in X_train we take 2 column that is review and education and in y_train we take purchased column
* Test data size is specified as 20% of the dataset using the test_size=0.2 parameter.

In [183]:
X_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

## import ordinal encoder

In [184]:
from sklearn.preprocessing import OrdinalEncoder

In [185]:
X_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

## Create object of ordinal encoding

In [186]:
oe =OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [187]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [188]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

## insights 
* we fit the data on only X_train
* but we transform the data on both x_train and X_test

In [189]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [190]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

## insights
* compare this result with the above data it show correct order as per given
* i.e Poor = 1 , School = 0

# import Label encoder

In [191]:
from sklearn.preprocessing import LabelEncoder

## create object of labelencoder

In [192]:
le = LabelEncoder()

In [193]:
le.fit(y_train)

LabelEncoder()

In [194]:
y_train= le.transform(y_train)
y_test= le.transform(y_test)

# insights 
* we fit the data on only y_train
* but we transform the data on both y_train and y_test

In [195]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [196]:
Y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

## insight
* here is 0 shows 'NO' and 1 shows 'Yes'